apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer  # Позволяет доступ к сервису снаружи
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
